apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-storage-vm
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: pxd.portworx.com
parameters:
  repl: "2"
  sharedv4: "true"
  sharedv4_mount_options: vers=3.0,nolock
volumeBindingMode: Immediate
allowVolumeExpansion: true
