apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: px-storage-vm
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
      volumeMode: Filesystem
  cloneStrategy: csi-clone
